// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FlightPlanReceived.proto

#include "FlightPlanReceived.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace xpilot {
constexpr FlightPlanReceived::FlightPlanReceived(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : flight_plan_(nullptr){}
struct FlightPlanReceivedDefaultTypeInternal {
  constexpr FlightPlanReceivedDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~FlightPlanReceivedDefaultTypeInternal() {}
  union {
    FlightPlanReceived _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT FlightPlanReceivedDefaultTypeInternal _FlightPlanReceived_default_instance_;
}  // namespace xpilot
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_FlightPlanReceived_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_FlightPlanReceived_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_FlightPlanReceived_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_FlightPlanReceived_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::xpilot::FlightPlanReceived, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::xpilot::FlightPlanReceived, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::xpilot::FlightPlanReceived, flight_plan_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::xpilot::FlightPlanReceived)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::xpilot::_FlightPlanReceived_default_instance_),
};

const char descriptor_table_protodef_FlightPlanReceived_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030FlightPlanReceived.proto\022\006xpilot\032\020Flig"
  "htPlan.proto\"R\n\022FlightPlanReceived\022,\n\013fl"
  "ight_plan\030\001 \001(\0132\022.xpilot.FlightPlanH\000\210\001\001"
  "B\016\n\014_flight_planB\031\252\002\026Vatsim.Xpilot.Proto"
  "bufb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_FlightPlanReceived_2eproto_deps[1] = {
  &::descriptor_table_FlightPlan_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_FlightPlanReceived_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FlightPlanReceived_2eproto = {
  false, false, 171, descriptor_table_protodef_FlightPlanReceived_2eproto, "FlightPlanReceived.proto", 
  &descriptor_table_FlightPlanReceived_2eproto_once, descriptor_table_FlightPlanReceived_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_FlightPlanReceived_2eproto::offsets,
  file_level_metadata_FlightPlanReceived_2eproto, file_level_enum_descriptors_FlightPlanReceived_2eproto, file_level_service_descriptors_FlightPlanReceived_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_FlightPlanReceived_2eproto_getter() {
  return &descriptor_table_FlightPlanReceived_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_FlightPlanReceived_2eproto(&descriptor_table_FlightPlanReceived_2eproto);
namespace xpilot {

// ===================================================================

class FlightPlanReceived::_Internal {
 public:
  using HasBits = decltype(std::declval<FlightPlanReceived>()._has_bits_);
  static const ::xpilot::FlightPlan& flight_plan(const FlightPlanReceived* msg);
  static void set_has_flight_plan(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::xpilot::FlightPlan&
FlightPlanReceived::_Internal::flight_plan(const FlightPlanReceived* msg) {
  return *msg->flight_plan_;
}
void FlightPlanReceived::clear_flight_plan() {
  if (flight_plan_ != nullptr) flight_plan_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
FlightPlanReceived::FlightPlanReceived(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:xpilot.FlightPlanReceived)
}
FlightPlanReceived::FlightPlanReceived(const FlightPlanReceived& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_flight_plan()) {
    flight_plan_ = new ::xpilot::FlightPlan(*from.flight_plan_);
  } else {
    flight_plan_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:xpilot.FlightPlanReceived)
}

void FlightPlanReceived::SharedCtor() {
flight_plan_ = nullptr;
}

FlightPlanReceived::~FlightPlanReceived() {
  // @@protoc_insertion_point(destructor:xpilot.FlightPlanReceived)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FlightPlanReceived::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete flight_plan_;
}

void FlightPlanReceived::ArenaDtor(void* object) {
  FlightPlanReceived* _this = reinterpret_cast< FlightPlanReceived* >(object);
  (void)_this;
}
void FlightPlanReceived::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FlightPlanReceived::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void FlightPlanReceived::Clear() {
// @@protoc_insertion_point(message_clear_start:xpilot.FlightPlanReceived)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(flight_plan_ != nullptr);
    flight_plan_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FlightPlanReceived::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .xpilot.FlightPlan flight_plan = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_flight_plan(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FlightPlanReceived::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xpilot.FlightPlanReceived)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .xpilot.FlightPlan flight_plan = 1;
  if (_internal_has_flight_plan()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::flight_plan(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xpilot.FlightPlanReceived)
  return target;
}

size_t FlightPlanReceived::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xpilot.FlightPlanReceived)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .xpilot.FlightPlan flight_plan = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *flight_plan_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FlightPlanReceived::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:xpilot.FlightPlanReceived)
  GOOGLE_DCHECK_NE(&from, this);
  const FlightPlanReceived* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FlightPlanReceived>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:xpilot.FlightPlanReceived)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:xpilot.FlightPlanReceived)
    MergeFrom(*source);
  }
}

void FlightPlanReceived::MergeFrom(const FlightPlanReceived& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:xpilot.FlightPlanReceived)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_flight_plan()) {
    _internal_mutable_flight_plan()->::xpilot::FlightPlan::MergeFrom(from._internal_flight_plan());
  }
}

void FlightPlanReceived::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:xpilot.FlightPlanReceived)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlightPlanReceived::CopyFrom(const FlightPlanReceived& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xpilot.FlightPlanReceived)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlightPlanReceived::IsInitialized() const {
  return true;
}

void FlightPlanReceived::InternalSwap(FlightPlanReceived* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(flight_plan_, other->flight_plan_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FlightPlanReceived::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_FlightPlanReceived_2eproto_getter, &descriptor_table_FlightPlanReceived_2eproto_once,
      file_level_metadata_FlightPlanReceived_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace xpilot
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::xpilot::FlightPlanReceived* Arena::CreateMaybeMessage< ::xpilot::FlightPlanReceived >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xpilot::FlightPlanReceived >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
