// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PostConsoleMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PostConsoleMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PostConsoleMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PostConsoleMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PostConsoleMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PostConsoleMessage_2eproto;
namespace xpilot {
class PostConsoleMessage;
struct PostConsoleMessageDefaultTypeInternal;
extern PostConsoleMessageDefaultTypeInternal _PostConsoleMessage_default_instance_;
}  // namespace xpilot
PROTOBUF_NAMESPACE_OPEN
template<> ::xpilot::PostConsoleMessage* Arena::CreateMaybeMessage<::xpilot::PostConsoleMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xpilot {

enum PostConsoleMessage_MessageType : int {
  PostConsoleMessage_MessageType_INFORMATION = 0,
  PostConsoleMessage_MessageType_WARNING = 1,
  PostConsoleMessage_MessageType_ERROR = 2,
  PostConsoleMessage_MessageType_PostConsoleMessage_MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  PostConsoleMessage_MessageType_PostConsoleMessage_MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool PostConsoleMessage_MessageType_IsValid(int value);
constexpr PostConsoleMessage_MessageType PostConsoleMessage_MessageType_MessageType_MIN = PostConsoleMessage_MessageType_INFORMATION;
constexpr PostConsoleMessage_MessageType PostConsoleMessage_MessageType_MessageType_MAX = PostConsoleMessage_MessageType_ERROR;
constexpr int PostConsoleMessage_MessageType_MessageType_ARRAYSIZE = PostConsoleMessage_MessageType_MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PostConsoleMessage_MessageType_descriptor();
template<typename T>
inline const std::string& PostConsoleMessage_MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PostConsoleMessage_MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PostConsoleMessage_MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PostConsoleMessage_MessageType_descriptor(), enum_t_value);
}
inline bool PostConsoleMessage_MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PostConsoleMessage_MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PostConsoleMessage_MessageType>(
    PostConsoleMessage_MessageType_descriptor(), name, value);
}
// ===================================================================

class PostConsoleMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xpilot.PostConsoleMessage) */ {
 public:
  inline PostConsoleMessage() : PostConsoleMessage(nullptr) {}
  ~PostConsoleMessage() override;
  explicit constexpr PostConsoleMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PostConsoleMessage(const PostConsoleMessage& from);
  PostConsoleMessage(PostConsoleMessage&& from) noexcept
    : PostConsoleMessage() {
    *this = ::std::move(from);
  }

  inline PostConsoleMessage& operator=(const PostConsoleMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PostConsoleMessage& operator=(PostConsoleMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PostConsoleMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const PostConsoleMessage* internal_default_instance() {
    return reinterpret_cast<const PostConsoleMessage*>(
               &_PostConsoleMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PostConsoleMessage& a, PostConsoleMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PostConsoleMessage* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PostConsoleMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PostConsoleMessage* New() const final {
    return new PostConsoleMessage();
  }

  PostConsoleMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PostConsoleMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PostConsoleMessage& from);
  void MergeFrom(const PostConsoleMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PostConsoleMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xpilot.PostConsoleMessage";
  }
  protected:
  explicit PostConsoleMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef PostConsoleMessage_MessageType MessageType;
  static constexpr MessageType INFORMATION =
    PostConsoleMessage_MessageType_INFORMATION;
  static constexpr MessageType WARNING =
    PostConsoleMessage_MessageType_WARNING;
  static constexpr MessageType ERROR =
    PostConsoleMessage_MessageType_ERROR;
  static inline bool MessageType_IsValid(int value) {
    return PostConsoleMessage_MessageType_IsValid(value);
  }
  static constexpr MessageType MessageType_MIN =
    PostConsoleMessage_MessageType_MessageType_MIN;
  static constexpr MessageType MessageType_MAX =
    PostConsoleMessage_MessageType_MessageType_MAX;
  static constexpr int MessageType_ARRAYSIZE =
    PostConsoleMessage_MessageType_MessageType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  MessageType_descriptor() {
    return PostConsoleMessage_MessageType_descriptor();
  }
  template<typename T>
  static inline const std::string& MessageType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MessageType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MessageType_Name.");
    return PostConsoleMessage_MessageType_Name(enum_t_value);
  }
  static inline bool MessageType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MessageType* value) {
    return PostConsoleMessage_MessageType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kTimestampFieldNumber = 1,
    kTypeFieldNumber = 3,
  };
  // optional string message = 2;
  bool has_message() const;
  private:
  bool _internal_has_message() const;
  public:
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  const PROTOBUF_NAMESPACE_ID::Timestamp& timestamp() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT PROTOBUF_NAMESPACE_ID::Timestamp* release_timestamp();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_timestamp() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_timestamp();
  public:
  void unsafe_arena_set_allocated_timestamp(
      PROTOBUF_NAMESPACE_ID::Timestamp* timestamp);
  PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_timestamp();

  // optional .xpilot.PostConsoleMessage.MessageType type = 3;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::xpilot::PostConsoleMessage_MessageType type() const;
  void set_type(::xpilot::PostConsoleMessage_MessageType value);
  private:
  ::xpilot::PostConsoleMessage_MessageType _internal_type() const;
  void _internal_set_type(::xpilot::PostConsoleMessage_MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:xpilot.PostConsoleMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  PROTOBUF_NAMESPACE_ID::Timestamp* timestamp_;
  int type_;
  friend struct ::TableStruct_PostConsoleMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PostConsoleMessage

// .google.protobuf.Timestamp timestamp = 1;
inline bool PostConsoleMessage::_internal_has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != nullptr;
}
inline bool PostConsoleMessage::has_timestamp() const {
  return _internal_has_timestamp();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& PostConsoleMessage::_internal_timestamp() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp&>(
      PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& PostConsoleMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:xpilot.PostConsoleMessage.timestamp)
  return _internal_timestamp();
}
inline void PostConsoleMessage::unsafe_arena_set_allocated_timestamp(
    PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  timestamp_ = timestamp;
  if (timestamp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xpilot.PostConsoleMessage.timestamp)
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PostConsoleMessage::release_timestamp() {
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PostConsoleMessage::unsafe_arena_release_timestamp() {
  // @@protoc_insertion_point(field_release:xpilot.PostConsoleMessage.timestamp)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = timestamp_;
  timestamp_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PostConsoleMessage::_internal_mutable_timestamp() {
  
  if (timestamp_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    timestamp_ = p;
  }
  return timestamp_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PostConsoleMessage::mutable_timestamp() {
  // @@protoc_insertion_point(field_mutable:xpilot.PostConsoleMessage.timestamp)
  return _internal_mutable_timestamp();
}
inline void PostConsoleMessage::set_allocated_timestamp(PROTOBUF_NAMESPACE_ID::Timestamp* timestamp) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(timestamp));
    if (message_arena != submessage_arena) {
      timestamp = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:xpilot.PostConsoleMessage.timestamp)
}

// optional string message = 2;
inline bool PostConsoleMessage::_internal_has_message() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PostConsoleMessage::has_message() const {
  return _internal_has_message();
}
inline void PostConsoleMessage::clear_message() {
  message_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PostConsoleMessage::message() const {
  // @@protoc_insertion_point(field_get:xpilot.PostConsoleMessage.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PostConsoleMessage::set_message(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xpilot.PostConsoleMessage.message)
}
inline std::string* PostConsoleMessage::mutable_message() {
  // @@protoc_insertion_point(field_mutable:xpilot.PostConsoleMessage.message)
  return _internal_mutable_message();
}
inline const std::string& PostConsoleMessage::_internal_message() const {
  return message_.Get();
}
inline void PostConsoleMessage::_internal_set_message(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PostConsoleMessage::_internal_mutable_message() {
  _has_bits_[0] |= 0x00000001u;
  return message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PostConsoleMessage::release_message() {
  // @@protoc_insertion_point(field_release:xpilot.PostConsoleMessage.message)
  if (!_internal_has_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return message_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PostConsoleMessage::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:xpilot.PostConsoleMessage.message)
}

// optional .xpilot.PostConsoleMessage.MessageType type = 3;
inline bool PostConsoleMessage::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PostConsoleMessage::has_type() const {
  return _internal_has_type();
}
inline void PostConsoleMessage::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::xpilot::PostConsoleMessage_MessageType PostConsoleMessage::_internal_type() const {
  return static_cast< ::xpilot::PostConsoleMessage_MessageType >(type_);
}
inline ::xpilot::PostConsoleMessage_MessageType PostConsoleMessage::type() const {
  // @@protoc_insertion_point(field_get:xpilot.PostConsoleMessage.type)
  return _internal_type();
}
inline void PostConsoleMessage::_internal_set_type(::xpilot::PostConsoleMessage_MessageType value) {
  _has_bits_[0] |= 0x00000002u;
  type_ = value;
}
inline void PostConsoleMessage::set_type(::xpilot::PostConsoleMessage_MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:xpilot.PostConsoleMessage.type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace xpilot

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::xpilot::PostConsoleMessage_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xpilot::PostConsoleMessage_MessageType>() {
  return ::xpilot::PostConsoleMessage_MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PostConsoleMessage_2eproto
