#pragma once

#define VERSION_MAJOR 3
#define VERSION_MINOR 0
#define VERSION_PATCH 0

#define STRINGIFY(x) #x
#define VERSION_STR(A,B,C) STRINGIFY(A) "." STRINGIFY(B) "." STRINGIFY(C)

#define VER_FILEVERSION             VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH
#define VER_FILEVERSION_STR         VERSION_STR(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)

#define VER_PRODUCTVERSION          VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH
#define VER_PRODUCTVERSION_STR      VERSION_STR(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)

#define VER_COMPANYNAME_STR         "Justin Shannon"
#define VER_FILEDESCRIPTION_STR     "xPilot"
#define VER_INTERNALNAME_STR        "xPilot"
#define VER_LEGALCOPYRIGHT_STR      "Copyright (c) 2021 Justin Shannon"
#define VER_LEGALTRADEMARKS1_STR    "All Rights Reserved"
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR    "xPilot.exe"
#define VER_PRODUCTNAME_STR         "xPilot"
